# Generated by Django 6.0.3 on 2026-03-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
