# Generated by Django 6.0.3 on 2026-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
